//go:build ignore

// Makes the built-in font the web backend draws with, out of raylib's own, so
// that text on the web has the same letters in the same places as text on the
// desktop:
//
//   - defaultfont.png: the atlas, every letter drawn once.
//   - defaultfont.go: where each letter sits in it, and how far it moves the
//     pen, straight from raylib.
//
// Run it from the framework folder:
//
//	golib go run internal/device/makefont.go
//
// It opens a window nobody sees, as golib shot does, because raylib makes its
// font when a window opens. The font is raylib's, under the zlib license,
// which golib dist already puts in every game's THIRD-PARTY-LICENSES.txt.
package main

import (
	"bytes"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"
	"path/filepath"
	"unsafe"

	rl "github.com/gen2brain/raylib-go/raylib"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "makefont:", err)
		os.Exit(1)
	}
}

func run() error {
	rl.SetTraceLogLevel(rl.LogWarning)
	rl.SetConfigFlags(rl.FlagWindowHidden)
	rl.InitWindow(64, 64, "makefont")
	defer rl.CloseWindow()
	if !rl.IsWindowReady() {
		return fmt.Errorf("could not open a window, which raylib needs before it makes its font")
	}

	font := rl.GetFontDefault()
	if font.Texture.ID == 0 || font.CharsCount == 0 {
		return fmt.Errorf("raylib gave no default font")
	}
	count := int(font.CharsCount)
	recs := unsafe.Slice(font.Recs, count)
	glyphs := unsafe.Slice(font.Chars, count)

	picture, err := atlas(font)
	if err != nil {
		return err
	}
	dir := filepath.Join("internal", "device")
	if err := writePNG(filepath.Join(dir, "defaultfont.png"), picture); err != nil {
		return err
	}
	if err := writeTable(filepath.Join(dir, "defaultfont.go"), font, recs, glyphs); err != nil {
		return err
	}
	fmt.Printf("makefont: %d letters, %d pixels high, on a %d by %d atlas\n",
		count, font.BaseSize, font.Texture.Width, font.Texture.Height)
	return nil
}

// atlas reads the font's texture back as a picture, its top row first.
func atlas(font rl.Font) (*image.NRGBA, error) {
	read := rl.LoadImageFromTexture(font.Texture)
	defer rl.UnloadImage(read)
	rl.ImageFormat(read, rl.UncompressedR8g8b8a8)
	width, height := int(read.Width), int(read.Height)
	if width == 0 || height == 0 {
		return nil, fmt.Errorf("the font's atlas is %d by %d", width, height)
	}
	picture := image.NewNRGBA(image.Rect(0, 0, width, height))
	for y := range height {
		for x := range width {
			c := rl.GetImageColor(*read, int32(x), int32(y))
			picture.SetNRGBA(x, y, color.NRGBA{R: c.R, G: c.G, B: c.B, A: c.A})
		}
	}
	return picture, nil
}

func writePNG(path string, picture *image.NRGBA) error {
	var file bytes.Buffer
	if err := png.Encode(&file, picture); err != nil {
		return err
	}
	return os.WriteFile(path, file.Bytes(), 0o644)
}

// writeTable writes the Go file the web backend reads the letters from.
func writeTable(path string, font rl.Font, recs []rl.Rectangle, glyphs []rl.GlyphInfo) error {
	var out bytes.Buffer
	fmt.Fprintf(&out, `//go:build js

// Code generated by makefont.go. DO NOT EDIT.

package device

// The built-in font, taken from raylib's own so that both backends draw the
// same letters. defaultFontGlyphs holds one letter per entry, in the order
// raylib keeps them, and defaultfont.png is the atlas they are cut from.

// defaultFontBaseSize is the height the letters were drawn at, in pixels.
// Text at another size is this one scaled, and defaultFontPadding is the
// space raylib left around each letter in the atlas.
const (
	defaultFontBaseSize = %d
	defaultFontPadding  = %d
)

// defaultFontGlyph is one letter: where it sits in the atlas, where it goes
// from the pen, and how far it moves the pen on.
type defaultFontGlyph struct {
	Value                  rune
	X, Y, Width, Height    float32
	OffsetX, OffsetY       int32
	AdvanceX               int32
}

var defaultFontGlyphs = [...]defaultFontGlyph{
`, font.BaseSize, font.CharsPadding)
	for i := range glyphs {
		r, g := recs[i], glyphs[i]
		fmt.Fprintf(&out, "\t{%d, %g, %g, %g, %g, %d, %d, %d},\n",
			g.Value, r.X, r.Y, r.Width, r.Height, g.OffsetX, g.OffsetY, g.AdvanceX)
	}
	out.WriteString("}\n")
	return os.WriteFile(path, out.Bytes(), 0o644)
}
